import { ArrowUpRight, Download, Lightbulb, MousePointerClick, Target, TrendingUp } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";
import { PerformanceChart } from "@/components/insights/performance-chart";

export default function InsightsPage() {
  return <div className="page-wrap">
    <PageHeading eyebrow="Performance intelligence · Last 7 days" title="The system is learning." description="Seeded prototype metrics show how campaign performance becomes reusable strategy—not another dashboard nobody checks." actions={<button className="button button-ghost"><Download size={13}/> Export report</button>} />
    <div className="grid-4">{[[MousePointerClick,'4.8%','Click-through rate','+18.4%'],[Target,'28','Conversions','+33.3%'],[TrendingUp,'3.1×','Best pattern lift','Founder story'],[Lightbulb,'7','Patterns learned','+2 new']].map(([I,v,l,t])=>{const Icon=I as typeof MousePointerClick;return <div className="card card-pad metric-card" key={String(l)}><span className="metric-icon"><Icon size={15}/></span><div className="metric-value">{String(v)}</div><div className="metric-label">{String(l)}</div><span className="metric-trend">{String(t)}</span></div>})}</div>
    <div className="insights-layout"><section className="card card-pad"><div className="card-head"><div><div className="card-note">Engagement signal</div><h2 className="section-title" style={{marginTop:5}}>Click-through rate</h2></div><div style={{display:'flex',gap:11,fontSize:9,color:'#79837f'}}><span>● Northwind</span><span style={{color:'#aab3af'}}>┄ Benchmark</span></div></div><PerformanceChart/></section>
      <aside className="card digest"><div className="brief-kicker">Analyst’s digest</div><h2 className="section-title" style={{marginTop:7}}>What changed this week</h2>{[['Lead with the operator, not the tool','Posts that name a real workflow friction are earning 1.8× more qualified clicks.'],['Proof is carrying conversion','Specific numbers in the first four lines correlate with 34% higher landing-page intent.'],['Email needs a tighter opening','Your email CTR trails LinkedIn; test the strongest social hook as the subject line.']].map(([t,c])=><div className="digest-item" key={t}><div className="digest-title">{t}</div><div className="digest-copy">{c}</div></div>)}</aside>
    </div>
    <section style={{marginTop:16}}><div className="card-head"><div><div className="card-note">Reusable intelligence</div><h2 className="section-title" style={{marginTop:5}}>Learned patterns</h2></div><span className="tag tag-lime">7 active</span></div><div className="grid-3">{[['3.1×','Founder stories','Engagement lift · n=18'],['1.8×','Pain-led openings','Qualified CTR lift · n=24'],['+34%','Numbers above fold','Conversion intent · n=15']].map(([lift,t,meta])=><article className="pattern-card" key={t}><div className="pattern-lift">{lift}</div><div className="pattern-copy"><strong style={{display:'block',fontSize:12,marginBottom:4,color:'#17201d'}}>{t}</strong>{meta}</div><span className="tag">Applied to next plan <ArrowUpRight size={10}/></span></article>)}</div></section>
  </div>;
}
